### ISSUE TITLE
Error when using your repo

### ISSUE THREAD

**Issue by isrgish** [sdrausty/sdrausty.github.io#2]
This is the error I get.

$ apt update
Hit:1 https://xeffyr.github.io/termux-x-repository termux InRelease
Hit:2 https://termux.net stable InRelease
Ign:3 https://sdrusty.github.io/repo termux InRelease
Ign:4 https://sdrusty.github.io/repo termux Release
Ign:5 https://sdrusty.github.io/repo termux/extras all Packages
Ign:6 https://sdrusty.github.io/repo termux/extras i686 Packages
Ign:5 https://sdrusty.github.io/repo termux/extras all Packages
Ign:6 https://sdrusty.github.io/repo termux/extras i686 Packages
Hit:7 https://grimler.se root InRelease
Ign:5 https://sdrusty.github.io/repo termux/extras all Packages
Ign:6 https://sdrusty.github.io/repo termux/extras i686 Packages
Ign:5 https://sdrusty.github.io/repo termux/extras all Packages
Err:6 https://sdrusty.github.io/repo termux/extras i686 Packages
  404  Not Found
Reading package lists... Done
E: Failed to fetch https://sdrusty.github.io/repo/dists/termux/extras/binary-i686/Packages  404  Not Found
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by SDRausty** [comment]
This repository has been deleted.
